### ISSUE TITLE
Docker image missing

### ISSUE THREAD

**Issue by sisygoboom** [Someguy123/hive-docker#8]
`./run.sh docker-full`
generates error
`Error response from daemon: No such image: someguy123/hive:latest-full`

**Comment by DataSteam2019** [comment]
I encountered the same issue. Have you solve this problem?

**Comment by sisygoboom** [comment]
I used gtg's image instead http://gtg.openhive.network/get/hivemind/hivemind-20210216-1.24rc0%2Bebc75a89.dump (that's an old one btw)

**Comment by DataSteam2019** [comment]
@sisygoboom Thank you! but this link seems invalid now. Were you also trying to dockerize the full node? May I ask if you have any references about how to dockerize the full node except this Github repo? Do you know where they put the new image or updates? I tried to search for it for a while but I found nothing...

**Comment by sisygoboom** [comment]
You can seed the entire Blockchain using the undockerised version  https://gitlab.syncad.com/hive/hive

Privex also have managed solutions

Gandalf's blog also has information for setting up a node [blog](https://peakd.com/hive-160391/@gtg/hive-pressure-3-catching-up-with-the-head-block).

**Comment by DataSteam2019** [comment]
Thank you for your help! I will check those.

**Comment by Someguy123** [comment]
There's no longer a `latest-full` because full nodes now use the same image as witness nodes :)

I'm closing this issue since it's no longer relavent to modern Hive.
